Controllers/Components/NumberCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebVPP.Extension;
using WebVPP.ModelViews;

namespace WebVPP.Controllers.Components
{
	public class NumberCartViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			var cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>("GioHang");
			return View(cart);
		}
	}
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebVPP.Models;
using PagedList.Core;

namespace WebVPP.Controllers
{
    public class ProductController : Controller
    {
        private readonly BtVppContext _context;
        public ProductController(BtVppContext context)
        {
            _context = context;
        }


        [Route("shop.html", Name = "ShopProduct")]
        public IActionResult Index(int? page)
        {
            try
            {
                var pageNumber = page == null || page <= 0 ? 1 : page.Value;
                var pageSize = 6;
                var lsProduct = _context.Products
                    .Include(x => x.Cat)
                    .AsNoTracking()
                    .OrderByDescending(x => x.ProductId);
                PagedList<Product> models = new PagedList<Product>(lsProduct, pageNumber, pageSize);
                ViewBag.CurrentPage = pageNumber;
                return View(models);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [Route("search.html")]
        public async Task<IActionResult> Search(string txtSearch, int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 6;
            var products = _context.Products.Where(m => m.ProductName.Contains(txtSearch))
                .Select(m => new Product()
                {
                    ProductName = m.ProductName,
                    Thumb = m.Thumb,
                    Price = m.Price
                });
            PagedList<Product> models = new PagedList<Product>(products, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View("Index", models);
        }

        [Route("/{Name}", Name = "ListProduct")]
        public IActionResult List(string name, int page = 1)
        {
            try
            {
                var pageSize = 5;
                var danhmuc = _context.Categories.AsNoTracking().SingleOrDefault(x => x.CatName == name);
                var lsProduct = _context.Products
                    .Include(x => x.Cat)
                    .AsNoTracking()
                    .Where(x => x.CatId == danhmuc.CatId)
                    .OrderByDescending(x => x.DateCreate);
                PagedList<Product> models = new PagedList<Product>(lsProduct, page, pageSize);
                ViewBag.CurrentPage = page;
                ViewBag.CurrentCat = danhmuc;
                return View(models);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [Route("/{ProductName}-{id}.html", Name = "ProductDetails")]
        public IActionResult Details(int id)
        {
            try
            {
                var product = _context.Products.Include(x => x.Cat).FirstOrDefault(x => x.ProductId == id);
                if (product == null)
                {
                    return RedirectToAction("Index");
                }
                var lsProduct = _context.Products.AsNoTracking()
                    .Where(x => x.CatId == product.CatId && x.ProductId != id)
                    .OrderByDescending(x => x.DateCreate)
                    .Take(4)
                    .ToList();
                ViewBag.SanPham = lsProduct;

                return View(product);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Views/Shared/_FooterPartialView.cshtml
<footer class="footer spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__about__logo">
                        <a href="./index.html"><img src="img/logo.png" alt=""></a>
                    </div>
                    <ul>
                        <li>Address: Hà Đông, Hà Nội</li>
                        <li>Phone: 0988997292</li>
                        <li>Email: vup2203@gmail.com</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                <div class="footer__widget">
                    <h6>Useful Links</h6>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">About Our Shop</a></li>
                        <li><a href="#">Secure Shopping</a></li>
                        <li><a href="#">Delivery infomation</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="footer__widget">
                    <h6>Join Our Newsletter Now</h6>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__widget__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="footer__copyright">
                    <div class="footer__copyright__text">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                    <div class="footer__copyright__payment"><img src="img/payment-item.png" alt=""></div>
                </div>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_HeaderPartialView.cshtml
@using Newtonsoft.Json;
@using WebVPP.Models;
@using Microsoft.AspNetCore.Http;

<header class="header">
	<div class="header__top">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<div class="header__top__left">
						<ul>
							<li><i class="fa fa-envelope"></i> vup2203@gmail.com</li>
							<li>Chào mừng đến với văn phòng phẩm</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-6 col-md-6">
					<div class="header__top__right">
						<div class="header__top__right__social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-linkedin"></i></a>
							<a href="#"><i class="fa fa-pinterest-p"></i></a>
						</div>
						<div class="header__top__right__auth">
							@if (ViewContext.HttpContext.Session.GetString("UserName") == null)
							{
								<a asp-controller="Account" asp-action="Login"><i class="fa fa-user"></i>Đăng nhập </a>
							}
							else
							{
							var user = JsonConvert.DeserializeObject<Account>(ViewContext.HttpContext.Session.GetString("UserName"));
							<a>Hello @user.FullName</a>
							<div>
								<a asp-controller="Account" asp-action="Logout">Đăng xuất</a>
							</div>
							}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="header__logo">
						<a href="./index.html"><img src="img/logo.png" alt=""></a>
					</div>
				</div>
				<div class="col-lg-6">
					<nav class="header__menu">
						<ul>
							<li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
							<li><a asp-controller="Product" asp-action="Index">Shop</a></li>
							<li><a asp-action="Contact" asp-controller="Home">Liên hệ</a></li>
						</ul>
					</nav>
				</div>
				<div class="col-lg-3">
					<div class="header__cart">
						<ul>
							<li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
							@await Component.InvokeAsync("NumberCart")
						</ul>
						<div class="header__cart__price">item: <span>$150.00</span></div>
					</div>
				</div>
			</div>
			<div class="humberger__open">
				<i class="fa fa-bars"></i>
			</div>
		</div>
	</div>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shop của Phong</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/staffcss/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/staffcss/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="#"><img src="img/logo.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
            </ul>
            <div class="header__cart__price">item: <span>$150.00</span></div>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__language">
                <img src="img/language.png" alt="">
                <div>English</div>
                <span class="arrow_carrot-down"></span>
                <ul>
                    <li><a href="#">Spanis</a></li>
                    <li><a href="#">English</a></li>
                </ul>
            </div>
            <div class="header__top__right__auth">
                <a href="#"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="./index.html">Home</a></li>
                <li><a href="./shop-grid.html">Shop</a></li>
                <li>
                    <a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="./shop-details.html">Shop Details</a></li>
                        <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                        <li><a href="./checkout.html">Check Out</a></li>
                        <li><a href="./blog-details.html">Blog Details</a></li>
                    </ul>
                </li>
                <li><a href="./blog.html">Blog</a></li>
                <li><a href="./contact.html">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                <li>Free Shipping for all Order of $99</li>
            </ul>
        </div>
    </div>
    <!-- Humberger End -->
    <!-- Header Section Begin -->
    @await Html.PartialAsync("_HeaderPartialView.cshtml")
    <!-- Header Section End -->

  @RenderBody()

    <!-- Footer Section Begin -->
  @await Html.PartialAsync("_FooterPartialView.cshtml")
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/staffjs/jquery-3.3.1.min.js"></script>
    <script src="~/staffjs/bootstrap.min.js"></script>
    <script src="~/staffjs/jquery.nice-select.min.js"></script>
    <script src="~/staffjs/jquery-ui.min.js"></script>
    <script src="~/staffjs/jquery.slicknav.js"></script>
    <script src="~/staffjs/mixitup.min.js"></script>
    <script src="~/staffjs/owl.carousel.min.js"></script>
    <script src="~/staffjs/main.js"></script>

    @await RenderSectionAsync("Scripts",required:false)

</body>

</html>