Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebVPP.Extension;
using WebVPP.ModelViews;

namespace WebVPP.Controllers
{
    public class CheckoutController : Controller
    {

        public List<CartItem> GioHang
        {
            get
            {
                var gh = HttpContext.Session.GetObjectFromJson<List<CartItem>>("GioHang");
                if (gh == default(List<CartItem>))
                {
                    gh = new List<CartItem>();
                }
                return gh;
            }
        }

        [Route("checkout.html")]
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>("GioHang");
            ViewBag.GioHang = cart;
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebVPP.Models;
using WebVPP.ModelViews;
using WebVPP.Extension;
using Newtonsoft.Json;

namespace WebVPP.Controllers
{
	public class ShoppingCartController : Controller
	{
		private readonly BtVppContext _context;
		public ShoppingCartController(BtVppContext context)
		{
			_context = context;
		}

		public List<CartItem> GioHang
		{
			get
			{
				var gh = HttpContext.Session.GetObjectFromJson<List<CartItem>>("GioHang");
				if (gh == default(List<CartItem>))
				{
					gh = new List<CartItem>();
				}
				return gh;
			}
		}


		[HttpPost]
		[Route("api/cart/add")]
		public IActionResult AddToCart(int productID, int? amount)
		{
			List<CartItem> giohang = GioHang;

			try
			{
				//Them san pham vao gio hang
				CartItem item = GioHang.SingleOrDefault(p => p.product.ProductId == productID);
				if (item != null) // da co => cap nhat so luong
				{
					item.amount = item.amount + amount.Value;
					//chuyen doi list danh sach thanh json
					//luu lai session
					HttpContext.Session.SetString("GioHang", JsonConvert.SerializeObject(giohang));
				}
				else
				{
					Product hh = _context.Products.SingleOrDefault(p => p.ProductId == productID);
					item = new CartItem
					{
						amount = amount.HasValue ? amount.Value : 1,
						product = hh
					};
					giohang.Add(item);//Them vao gio
				}

				//Luu lai Session
				HttpContext.Session.SetString("GioHang", JsonConvert.SerializeObject(giohang));
				return Json(new { success = true });
			}
			catch
			{
				return Json(new { success = false });
			}
		}

        [HttpPost]
        [Route("api/cart/update")]
        public IActionResult UpdateCart(int productID, int? amount)
        {
            //Lay gio hang ra de xu ly
            var giohang = HttpContext.Session.GetObjectFromJson<List<CartItem>>("GioHang");
            try
            {
                if (giohang != null)
                {
                    CartItem item = giohang.SingleOrDefault(p => p.product.ProductId == productID);
                    if (item != null && amount.HasValue) // da co -> cap nhat so luong
                    {
                        item.amount = amount.Value;
                    }
                    //Luu lai session
                    HttpContext.Session.SetString("GioHang", JsonConvert.SerializeObject(giohang));
                }
                return Json(new { success = true });
            }
            catch 
            {
                return Json(new { success = false });
            }
        }


        [HttpPost]
		[Route("api/cart/remove")]
		public ActionResult Remove(int productID)
		{
			try
			{
				List<CartItem> gioHang = GioHang;
				CartItem item = gioHang.SingleOrDefault(p => p.product.ProductId == productID);
				if (item != null)
				{
					gioHang.Remove(item);
				}
				//luu lai session
				HttpContext.Session.SetString("GioHang", JsonConvert.SerializeObject(gioHang));
				return Json(new { success = true });
			}
			catch
			{
				return Json(new { success = false });
			}
		}



        [Route("cart.html", Name = "Cart")]
        public IActionResult Index()
        {
            return View(GioHang);
        }
    }
}

Views/ShoppingCart/Index.cshtml
@using Newtonsoft.Json;
@using WebVPP.Models;
@using Microsoft.AspNetCore.Http;

@model List<WebVPP.ModelViews.CartItem>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h1>Thông tin đơn hàng</h1>
                    <div class="breadcrumb__option">
                        <a style="color : black" href="/">Trang chủ</a>
                        <i class="fa fa-chevron-right"></i>
                        <span style="color : black">Giỏ hàng</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th class="shoping__product">Sản phẩm</th>
                                <th>Giá tiền</th>
                                <th>Số lượng</th>
                                <th>Tổng tiền</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(Model != null && Model.Count() > 0)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img width="200" height="200" src="~/images/products/@item.product.Thumb" alt="">
                                            <h5>@item.product.ProductName</h5>
                                        </td>
                                        <td class="shoping__cart__price">
                                            @item.product.Price.Value.ToString("#,##0")VND
                                        </td>
                                        <td class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <div class="pro-qty">
                                                    <input data-mahh="@item.product.ProductId" data-dongia="@item.product.Price" class="cartItem" type="number" value="@item.amount">
                                                </div>
                                            </div>
                                        </td>
                                        <td class="shoping__cart__total">
                                            @item.TotalMoney.ToString("#,##0")VND
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <input type="button" value="X" class="removecart btn btn-primary" data-mahh="@item.product.ProductId"/>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__btns">
                    <a href="/shop.html" class="primary-btn cart-btn">Tiếp tục mua hàng</a>
                    <a href="#" class="primary-btn cart-btn cart-btn-right">
                        <span class="icon_loading"></span>
                        Upadate Cart
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__checkout">
                    <h5>Tổng đơn hàng</h5>
                    <ul>
                        <li>Tổng thành tiền<span>@Model.Sum(x => x.TotalMoney).ToString("#,##0")VND</span></li>
                    </ul>
                 @if (ViewContext.HttpContext.Session.GetString("UserName") == null)
                    {
                        <a href="@Url.Action("Login", "Account", new { returnUrl = Url.Action("Index", "Checkout") })" class="primary-btn">Thanh toán</a>

                    }
                    else {
                        <a href="/checkout.html" class="primary-btn">Thanh toán</a>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shoping Cart Section End -->
@section Scripts{
    <script>
        $(function () {
            function loadHeaderCart() {
                $('#numberCart').load("/AjaxContent/NumberCart");
            }
            $(".removecart").click(function () {
                var productid = $(this).attr("data-mahh");
                $.ajax({
                    url: "api/cart/remove",
                    type: "POST",
                    dataType: "JSON",
                    data: { productID: productid },
                    success: function (result) {
                        if (result.success) {
                            loadHeaderCart();//Reload lai gio hang
                            location.reload();
                        }
                    },
                    error: function (rs) {
                        alert("Remove Cart Error !")
                    }
                });
            });
            $(".cartItem").click(function () {
                var productid = $(this).attr("data-mahh");
                var soluong = parseInt($(this).val());
                $.ajax({
                    url: "api/cart/update",
                    type: "POST",
                    dataType: "JSON",
                    data: {
                        productID: productid,
                        amount: soluong
                    },
                    success: function (result) {
                        if (result.success) {
                            loadHeaderCart();//Reload lai gio hang
                            window.location = 'cart.html';
                        }
                    },
                    error: function (rs) {
                        alert("Cập nhật Cart Error !")
                    }
                });
            });
        });
    </script>
}